### PR TITLE
Add clintonb to django-commons

### LINKED ISSUE #118: ✋ [MEMBER] - clintonb
### Why do you want to join?

I am considering transferring https://github.com/jazzband/django-waffle so that I have greater administrative support. I'd rather not return it to independent status.

### Which project(s) are you looking to contribute to?

https://github.com/jazzband/django-waffle

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

### PR DESCRIPTION
**Pull request by cunla**
Fix #118

### CODE REVIEW

**Comment by tim-schilling** [comment]
Is this plan valid?

**Comment by cunla** [comment]
> Is this plan valid?

This is strange, not sure exactly what caused this.

**Comment by cunla** [comment]
What is even stranger is that running locally the plan shows different results. I think I have a different terraform version

**Comment by cunla** [comment]
Ok, looks better now!

**Pull request merged**
