### PR TITLE
Add giovannicimolin to django-commons

### LINKED ISSUE #134: ✋ [MEMBER] - giovannicimolin
### Why do you want to join?

I want to help maintain and contribute some changes and improvements to a few projects.

### Which project(s) are you looking to contribute to?

Django-fsm2 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

### PR DESCRIPTION
**Pull request by cunla**
Fix #134

### CODE REVIEW

**Review by tim-schilling — CHANGES_REQUESTED** [review]
I think they should be added as a member to Django-fsm2 so they have triage permissions

**Comment by Stormheg** [comment]
@cunla I added them as a member of django-fsm-2. Will this apply work? Or will this cause issues similar to https://github.com/django-commons/membership/pull/92 if they haven't accepted the invitation to join yet.

**Comment by cunla** [comment]
I think it is better adding them first to the org and only after confirming they are in the org adding them to various teams.

**Comment by tim-schilling** [comment]
The issue in #92 was a different case since the person didn't join ahead of time. Here the person is joining. Presumably, they'll accept the invitation promptly.

@cunla if your concern isn't technical, can you please expand on it for me?

**Comment by cunla** [comment]
> The issue in #92 was a different case since the person didn't join ahead of time. Here the person is joining. Presumably, they'll accept the invitation promptly.
> 
> @cunla if your concern isn't technical, can you please expand on it for me?

It is technical. I am not sure whether adding a non-org member to an org-team is possible.
Since the apply would only invite to the org and not directly add, the adding to the team part might fail.

**Review by Soham-047 — APPROVED** [review]

**Review by tim-schilling — APPROVED** [review]

**Pull request merged**
