### PR TITLE
Define new member requirements

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Review by williln — APPROVED** [review]
LGTM! Thank you!

**Review by cunla — COMMENTED** [review]
Isn't this better suited in the controls repo? Also it is mostly covered already here: https://github.com/django-commons/controls/blob/main/README.md?plain=1#L15-L16

**Comment by tim-schilling** [comment]
My reasoning was similar that of putting the inbound repo requirements here. It's public facing requirements that should be easily accessible by the members. Ideally, anything accessible to members should be in a single place which is this repo. What do you think?

However, it seems like discussions and projects will differ, but we can't control that since it's a GitHug architecture thing.

**Comment by ryancheley** [comment]
I agree that having the requirements here is a good idea. Can we update the controls repo to be a link back to this repo for membership requirements? That was there shouldn’t be any disagreement between the two repos.

**Comment by tim-schilling** [comment]
Good call, I overlooked that for sure. I added a reference to this file here: https://github.com/django-commons/controls/pull/59

**Review by Stormheg — APPROVED** [review]
LGTM

**Review by cunla — APPROVED** [review]

**Pull request merged**
