### PR TITLE
Updated references to playground repo to best-practices

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Comment by tim-schilling** [comment]
@cunla something tells me if we apply this we're going to run into problems.

**Comment by ryancheley** [comment]
Is it possible to create a new repo with the name we want and then remove the old one? I agree with @tim-schilling that running this looks like it will cause some issues, though my sense is more of a gut feeling than specific experience or knowledge of what this change will do.

**Comment by cunla** [comment]
I am not sure that's the way to go with this. It doesn't say it will make changes to the repo but destroy and create (when it changes things, it shows `~`).

I will update the repo manually and the tf state manually.

**Comment by cunla** [comment]
I updated the repo and teams manually (though not the team's descriptions) - Here is the PR: https://github.com/django-commons/membership/pull/127

**Pull request closed without merging**
