### PR TITLE
Add johnfraney to django-commons

### LINKED ISSUE #128: ✋ [MEMBER] - johnfraney
### Why do you want to join?

I'm looking to get back into Django development after a few years' hiatus, and contributing to open-source projects would be a great way to do that while giving back to the community. I respect the mission of Django Commons and it would be cool to be a part of it!

### Which project(s) are you looking to contribute to?

Any! I'm happy to contribute CI, type hints, unit tests, bugfixes, or maintenance tasks.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

### PR DESCRIPTION
**Pull request by cunla**
Fix #128

### CODE REVIEW

**Review by williln — APPROVED** [review]
Welcome @johnfraney!

**Comment by johnfraney** [comment]
Thank you, @williln!

**Comment by tim-schilling** [comment]
I've renamed whoiskrt2 to ghost because it appears there was a name change as per #114

**Comment by tim-schilling** [comment]
Ack. Ghost isn't a user.

**Pull request merged**
