### PR TITLE
Add projects list to our documentation.

### PR DESCRIPTION
**Pull request by tim-schilling**
This list should be information only and not the source of truth for projects.

### CODE REVIEW

**Comment by ryancheley** [comment]
this looks great … is there a way that we can have this automatically update when a new project is brought on (I’m sure there is, but I’m not sure what the best way to do it would be though!)

**Comment by tim-schilling** [comment]
I guess it comes back to, what's the purpose of this documentation? We could refer people to the repositories page on the org to see what projects are there. And we can refer people to the issues to find the joined date.

Regarding needing to do something based on the join date, @williln's source of truth sheet of projects and next actions should cover that.

I guess I'm arguing maybe we don't have the list here and use this page to route folks to the relevant areas.

**Review by cunla — APPROVED** [review]

**Review by Stormheg — APPROVED** [review]
Nice overview!

**Comment by williln** [comment]
I do agree with @tim-schilling that it's possible this list will go stale, and there are other places where this information can be found... but I also think there is value in having the list of projects very easily accessible, especially for projects who are considering joining Django Commons. Seeing other projects you know, use, and trust that are part of Django Commons increases the overall "trust" factor for the organization, I think. 

@tim-schilling would a compromise maybe be retaining this list until it gets too long to manage (at which point... yay, look how successful we are!), and then updating to point to the repositories link? I think it serves a valuable marketing purpose for now, but that probably won't always be the case.

**Review by williln — APPROVED** [review]

**Pull request merged**
